import React from "react";
import {
  CreatorIcon,
  SMEIcon,
  EnterpriseIcon,
  RealEstateIcon,
  FoodIcon,
  FashionIcon,
  HomeServicesIcon,
  HealthIcon,
  ElectronicsIcon,
  AutoIcon,
  EventsIcon,
  EducationIcon,
  ConstructionIcon,
} from "@/utils/constants/categoryIcons";

type BusinessType = "CREATOR" | "SME" | "ENTERPRISE";

export type Category = {
  id: string;
  title: string;
  icon: React.ReactNode;
  color: string;
  items: string[];
  businessType?: BusinessType;
};

const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "creator",
    title: "Creators",
    icon: <CreatorIcon />,
    color: "bg-indigo-100",
    businessType: "CREATOR",
    items: [
      "Designers",
      "Photographers",
      "Writers",
      "Influencers",
      "Video Editors",
      "Content Creators",
      "Animators",
      "Brand Strategists",
      "Streamers",
    ],
  },
  {
    id: "enterprise",
    title: "Enterprises",
    icon: <EnterpriseIcon />,
    color: "bg-yellow-100",
    businessType: "ENTERPRISE",
    items: [
      "Large Brands",
      "Corporations",
      "Distributors",
      "Manufacturers",
      "Wholesalers",
      "Agencies",
      "Franchises",
      "Government Contractors",
    ],
  },
  {
    id: "real-estate-1",
    title: "Real Estate & Housing",
    icon: <RealEstateIcon />,
    color: "bg-rose-50",
    businessType: "SME",
    items: [
      "Realtors",
      "Property Agents",
      "Shortlet Apartments",
      "Property Managers",
      "Home Rentals",
      "Land Sellers",
      "Movers & Relocation",
      "Interior Furnishing",
    ],
  },
  {
    id: "food-1",
    title: "Food & Drinks",
    icon: <FoodIcon />,
    color: "bg-red-50",
    businessType: "SME",
    items: [
      "Restaurants",
      "Bakeries",
      "Bars & Lounges",
      "Cafes",
      "Fast Food",
      "Food Vendors",
      "Caterers",
      "Snack & Small Chops",
    ],
  },
  {
    id: "fashion-1",
    title: "Fashion & Apparel",
    icon: <FashionIcon />,
    color: "bg-purple-50",
    businessType: "SME",
    items: [
      "Tailors",
      "Salons & Barbers",
      "Nail Technicians",
      "Shoe Makers",
      "Boutiques",
      "Makeup Artists",
      "Fashion Designers",
      "Laundry & Dry Cleaning",
    ],
  },
  {
    id: "services-1",
    title: "Home Services",
    icon: <HomeServicesIcon />,
    color: "bg-blue-50",
    businessType: "SME",
    items: [
      "Electricians",
      "AC/Gen Repair",
      "Security",
      "Plumbers",
      "Cleaners",
      "Gardening",
      "Pest Control",
      "Home Maintenance",
    ],
  },
  {
    id: "health-1",
    title: "Health & Wellness",
    icon: <HealthIcon />,
    color: "bg-green-50",
    businessType: "SME",
    items: [
      "Clinics",
      "Labs",
      "Dentists",
      "Pharmacies",
      "Physiotherapy",
      "Opticians",
      "Massage Therapists",
      "Nutritionists",
    ],
  },
  {
    id: "electronics-1",
    title: "Electronics & Gadgets",
    icon: <ElectronicsIcon />,
    color: "bg-purple-50",
    businessType: "SME",
    items: [
      "Electronics Shops",
      "Supermarkets",
      "Computer Shops",
      "Gift Shops",
      "Phone Accessories",
      "Bookstores",
      "Game Stores",
      "Laptop Repair",
    ],
  },
  {
    id: "auto-1",
    title: "Automotive",
    icon: <AutoIcon />,
    color: "bg-yellow-50",
    businessType: "SME",
    items: [
      "Ride-hailing",
      "Auto Mechanics",
      "Toll Agencies",
      "Logistics",
      "Car Wash",
      "Spare Parts",
      "Vehicle Inspection",
      "Tyre Shops",
    ],
  },
  {
    id: "events-1",
    title: "Events & Entertainment",
    icon: <EventsIcon />,
    color: "bg-indigo-50",
    businessType: "SME",
    items: [
      "Event Planners",
      "Rentals",
      "Videographers",
      "Decorators",
      "DJs",
      "Caterers",
      "MC/Hosts",
      "Musicians & Bands",
    ],
  },
  {
    id: "education-1",
    title: "Education & Training",
    icon: <EducationIcon />,
    color: "bg-teal-50",
    businessType: "SME",
    items: [
      "Tutors",
      "Skills Academies",
      "Computer Training",
      "Music Lessons",
      "Language Schools",
      "Professional Courses",
      "Driving Schools",
      "E-Learning",
    ],
  },
  {
    id: "construction-1",
    title: "Construction & Trades",
    icon: <ConstructionIcon />,
    color: "bg-orange-50",
    businessType: "SME",
    items: [
      "Builders",
      "Welders",
      "Tilers",
      "Architects",
      "Surveyors",
      "Painters",
      "Carpenters",
      "Interior Designers",
    ],
  },
];

export { DEFAULT_CATEGORIES };
export type { BusinessType };
